### ISSUE TITLE
The app does not launch on Firefox.

### ISSUE THREAD

**Issue by witoldsz** [garethgd/hyperapp-frogger#1]
The screen is all blue, console looks like this:

```
Navigated to http://localhost:8081/
[WDS] Disconnected!
bundle.js:876:5
TypeError: CSS2Properties doesn't have an indexed property setter for '0'
bundle.js:221:11
Source map error: request failed with status 404
Resource URL: http://localhost:8081/bundle.js
Source Map URL: sockjs.js.map[Learn More]
```

Firefox Quantum
59.0.2 (64-bit)
Mozilla Firefox for Ubuntu
canonical - 1.0

**Comment by garethgd** [comment]
Thanks for spotting this. Investigating now.

**Comment by nattthebear** [comment]
Also seeing this in Firefox 59.0.2 (64 bit) on Windows 7

**Comment by garethgd** [comment]
Fixed by removing the style properties from svg elements in Main.js and Game.js.
